### ISSUE TITLE
Design a splash screen for the app

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#1]
**Making a splash screen in Flutter is quite easy :)**

You can easily make on for this , You don't need to think about routing issues , or where to route your splash screen to.You can just make the page in a single dart file.

This will be really beneficial to you if you are starting to work with Flutter , if you need any more info just comment `here.```

**Comment by LemonDrop847** [comment]
Hey, Can i work on this? @diptanshumahish

**Comment by Sriver27** [comment]
I can work it out. Can you assign this issue to me? @diptanshumahish

**Comment by diptanshumahish** [comment]
> Hey, Can I work on this? @diptanshumahish And, do you need a landing page or just a splash screen?

You just need to design a splash screen for this app , that's it for now :) If you want the app logo you can tell me I'll provide you

**Comment by diptanshumahish** [comment]
> I can work it out. Can you assign this issue to me? @diptanshumahish

I can assign you for designing the settings page if you want to ?

**Comment by LemonDrop847** [comment]
> > Hey, Can I work on this? @diptanshumahish And, do you need a landing page or just a splash screen?
> 
> You just need to design a splash screen for this app , that's it for now :) If you want the app logo you can tell me I'll provide you

Yes that would be good, please provide the app logo.

**Comment by diptanshumahish** [comment]
you can use the one in the assets , that's the final logo , or you can refer to this figma file : https://www.figma.com/file/C3um1WXA1J76J1sLt53Adt/watch-app-logo?node-id=0%3A1
