### ISSUE TITLE
Redesign the profile page

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#13]
# Redesign the profile page

## keypoints
1.The profile page is available, but has more scopes for redesign. You can provide Figma designs for the page as attachments, or directly share your ideas. Once the design is finalized we can start with the coding part.

2.You can use any other software other than Figma as well, such as Adobe XD, or even pen paper work too. Make sure your design follows the design principles from the other pages.

**Comment by Namya13Jain** [comment]
Kindly assign this issue to me

**Comment by Namya13Jain** [comment]
okay..thanks sir

**Comment by RunTerror** [comment]
Please assign this issue to me

**Comment by diptanshumahish** [comment]
> Please assign this issue to me 

You can work only on one issue for a project at a time, you are already assigned one

**Comment by radar101** [comment]
I would like to work for this issue. I will design the profile page using figma and the photoshop.

**Comment by Namya13Jain** [comment]
I want to work on this issue under JWOC

**Comment by diptanshumahish** [comment]
> I would like to work for this issue. I will design the profile page using figma and the photoshop. It's under JWOC.

Assigning this issue to you, good luck.
after you are done with the work , add your image file to the root directory itself , and make sure your file name is in the format of (your username_profilePage)
if any more questions do let me know.

**Comment by radar101** [comment]
Do I have to just design the profile page or code it as well ?

**Comment by diptanshumahish** [comment]
> Do I have to just design the profile page or code it as well ?

Just design

**Comment by radar101** [comment]
https://www.figma.com/file/ElZwZGeSoOEyACSUi44AyR/Untitled?node-id=0%3A1&t=0A2EEozasPz8w3UZ-1  
Will you please check if this design will work or not ?

**Comment by diptanshumahish** [comment]
> https://www.figma.com/file/ElZwZGeSoOEyACSUi44AyR/Untitled?node-id=0%3A1&t=0A2EEozasPz8w3UZ-1  
> 
> Will you please check if this design will work or not ? 
> 
> 

No man, check out the already made page designs and follow those desings please(The ones in the Discord channel). Please try to give it a more premium look, this looks too fancy

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by RunTerror** [comment]
Please assign me  this issue

**Comment by sagnik-sanyal** [comment]
Hey if possible please assign me this issue i want to work under jwoc, lets fiinsh this off

**Comment by Khushal747** [comment]
hey ,i want to work under JWOC ,please assign me this issue

**Comment by sagnik-sanyal** [comment]
Hey @diptanshumahish can you please have a look at the ui at https://www.figma.com/file/ulewPN9RHcvtlXFViwk4uB/Watch-Flutter?node-id=0%3A1&t=1qaJKJkMcmUjjsSG-1 , if there are some changes required you can comment in those files
