### ISSUE TITLE
Store user preferences locally

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#14]
# Local storage setup
The user settings such as Name, Age and Boolean values such as "isAdultContent", dark/light mode need to be stored locally, for usage on the next login. 

## keypoints
1.You can use any of the local storages such as "shared preferences" or any other of your choice, must be lightweight though.

2.The login will be through Google Firebase but it will be implemented later, for now make a function to store user details locally on successful login.

3. Make a function to get the data from the saved preferences and apply the settings, for now only the username, and dark/light mode. 

4. If any more changes /ideas come to you let me know

5. Let me know if you need any help with anything while working on the issue

**Comment by sagnik-sanyal** [comment]
Hey can you please elaborate upon the folder structure that we are going to follow . As of now i think feature first layer will do good where we can make a sharedpreferences service(singleton class). I am ready to work on this issue

**Comment by diptanshumahish** [comment]
@sagnik-sanyal yes the structure for now would be like the following key value pair order:
user_email : "",
user_fullName: "",
userAdult: bool,
theme: "dark"/"light",

for now we can implement only these, and you can get the data from the signup page, you will find the variables there itself, no need to store the password.
The dark/light mode can be taken from the profile page itself. 
that's all you need to do currently. 

For assigning the issue we will be doing that after 15th only

**Comment by sagnik-sanyal** [comment]
I want to work on this issue under JWOC.

**Comment by diptanshumahish** [comment]
> I want to work on this issue under JWOC.

All the best buddy, if you need any further information let me know.

**Comment by sagnik-sanyal** [comment]
Thanks for assigning

**Comment by diptanshumahish** [comment]
> Thanks for assigning

Hello bro, I just checked your code, ofcourse it is all correct I saw, but the thing is I guess the code could have been much simpler, we just needed a simple way to store the data through shared preferences. 

I believe that instead of creating a complete class and storing them using json, it would have been much more simpler if you would have just used the simple old school method of shared preferences

`prefs.setString("userFullname",(the sring used for storing name))`
similarly with the others as well using setInt, and setBool

and while calling the data we could have simply used the old method of 
`prefs.getString((userFullname))`

And these all could be inside a simple asynchronous function to get the job done.

I'm suggesting this because this project was meant to be beginner friendly, many developers would be confused about the code for that part, let me know what do you think.

**Comment by diptanshumahish** [comment]
> What my main motive was to simplify the setting the values in the function. Suppose we need to set a string value we need to call prefs.SetString instead in order to simplify the setValue function ( a.k.a setString,setBool,setStringList etc.) will also be the same but simplified version as it would take the required datatype and set it accordingly. I have also written comments so I don't think it would be an issue. Moreover the main purpose of making a model class was that it is always scalable as you can add whatever parameter later on and boom ! you are all set. No need to make a seperate function once again for storing the values

Yeah I agree scalability would be of course much more when using the model class. Anyways fine we can merge this.
