### ISSUE TITLE
Redesign the Login page and signup page top portion

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#15]
# Redesign the top portion for the Login and signup page

## keypoints
1. We already have a basic setup done for the page, focus mainly on the top portion (The black background region)
2.  Incase you have any further suggestions let me know 
3. Make your designs using Figma, Adobe XD or any equivalent software, and attach the prototype images here itself
4. For any further questions let me know.

**Comment by RunTerror** [comment]
Please assign this issue to me

**Comment by diptanshumahish** [comment]
> Please assign this issue to me 

Okay assigning you this task

**Comment by RunTerror** [comment]
Okay @diptanshumahish

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by RunTerror** [comment]
![Screenshot_1676814495](https://user-images.githubusercontent.com/113206442/219952654-e8f413cf-6511-4cf7-b2ec-b88627e56ce5.png)
![Screenshot_1676814500](https://user-images.githubusercontent.com/113206442/219952665-424aba34-ef2c-4fdb-b6dd-ec6a2e56192d.png)
i have make the white container scrollable and the background is fix can you suggest me more changes

**Comment by diptanshumahish** [comment]
> ![Screenshot_1676814495](https://user-images.githubusercontent.com/113206442/219952654-e8f413cf-6511-4cf7-b2ec-b88627e56ce5.png) ![Screenshot_1676814500](https://user-images.githubusercontent.com/113206442/219952665-424aba34-ef2c-4fdb-b6dd-ec6a2e56192d.png) i have make the white container scrollable and the background is fix can you suggest me more changes

Yeah good Idea, do one thing add this image screenshots, to the lib folder by renaming your files as (your github name)_signupPage and make a pull request, we can then  close this issue.

**Comment by RunTerror** [comment]
ok will doing this

**Comment by diptanshumahish** [comment]
> ok will doing this

Have you changed something in the code?

**Comment by RunTerror** [comment]
yes used stack at one place and change some width of textfield and signup button

**Comment by diptanshumahish** [comment]
> yes used stack at one place and change some width of textfield and signup button

Thanks for the contribution, merged it, good work!
