### ISSUE TITLE
Design the favorites page

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#16]
# Design the favorites page in this app

## keypoints
1. The favorites page has not been built yet, design the page.
2.  The design can be made using any software such as Figma, Adobe XD, etc and the finished designs can be attached here, you can see the app designs in the discord channel itself to get an idea of the app as a whole.
3.  Any design ideas are welcome, for this app the major theme colors are black and white.
4.  In case you have any queries feel free to ask here.

**Comment by sagnik-sanyal** [comment]
Waiting for PR #19 to be merged so that i can start implementing this feature and contribute under JWOC

**Comment by diptanshumahish** [comment]
> Waiting for PR #19 to be merged so that i can start implementing this feature and contribute under JWOC

check out my comment on the issue #14

**Comment by sagnik-sanyal** [comment]
@diptanshumahish do we have any ui design already made for this screen on figma or do we have to design it from scratch?

**Comment by diptanshumahish** [comment]
> @diptanshumahish do we have any ui design already made for this screen on figma or do we have to design it from scratch?

Nope we don't have any design yet. You have yo take ideas about the design principles from the other pages, and design the page.
basically yes you have to do it from scratch.

**Comment by sagnik-sanyal** [comment]
Ok first i will work on the designing of this page and later share the figma file with you and if approved will start coding for this page asap. I'm ready to contribute under JWOC

**Comment by diptanshumahish** [comment]
> Ok first i will work on the designing of this page and later share the figma file with you and if approved will start coding for this page asap. I'm ready to contribute under JWOC

Great you can start working on this. once done you can let me know.

**Comment by sagnik-sanyal** [comment]
@diptanshumahish pls check https://www.figma.com/file/ulewPN9RHcvtlXFViwk4uB/Watch-Flutter?node-id=103%3A349&t=cuU6LRppowW3zOrO-1 if you want to add something you can suggest me something related to favourites page

**Comment by sagnik-sanyal** [comment]
hey there the favourites page has been done. we should have some secondary color as well for the app pure black will not look good. pls suggest any changes if you want them. I also have an optional watch shop section which is totally optional. pls check @diptanshumahish

**Comment by diptanshumahish** [comment]
> hey there the favourites page has been done. we should have some secondary color as well for the app pure black will not look good. pls suggest any changes if you want them. I also have an optional watch shop section which is totally optional. pls check @diptanshumahish 

Yes the red colour works pretty well that you have used, I hope that wouldn't give rendering issues on the actual screen and not use up too much graphic.

We can use that red as the secondary colour.

For the shop section that looks cool but I guess we can keep it a side option, maybe we can implement it later with some actual service, maybe use sanity.io for it. ( we can keep those for the phase 2)

Other wise the design is good, do one thing, make a folder called (page designs) and rename your exported png file as your username and add the file to the repo. Great work!

**Comment by sagnik-sanyal** [comment]
Dont worry those red colors wouldn't cause much issues as we can also make those shades using custom painters which should be pretty easy to implement tbh

**Comment by diptanshumahish** [comment]
> Dont worry those red colors wouldn't cause much issues as we can also make those shades using custom painters which should be pretty easy to implement tbh

Yes yes if done using custom painters then good 👍 go forward and do the pull request

**Comment by sagnik-sanyal** [comment]
> > Dont worry those red colors wouldn't cause much issues as we can also make those shades using custom painters which should be pretty easy to implement tbh
> 
> Yes yes if done using custom painters then good 👍 go forward and do the pull request

Yeah my PR is merged so i think i can work on a new issue
