### ISSUE TITLE
Design of the particular categories page

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#18]
# Design individual category pages

## keypoints
1. The home screen has various sections like "for you", genre sections like horror, drama etc.
2. This page design needs to be done before we can start coding
3. The design should be done in such a way keeping in mind that all category pages will have a similar design, so yeah go forward and make designs.
4. you can check screenshots of other pages from the discord or ask me if you want.
5. Do comment if you want to work on this and let me know if you want anything else.

**Comment by Subrata-Rajak** [comment]
Hey @diptanshumahish, I am Subrata Rajak, a participant of JWOC. I am looking forward to contributing to some great flutter or app dev projects and I find this repo a good one to start with. Can you please assign me this issue, so that I can start with it!! And also let me know where I can find the designs...

**Comment by diptanshumahish** [comment]
Yes sure, go to the discord channel you will find the screenshots and also the explanation

**Comment by Udit-Shukla** [comment]
can u assign  me this issue?

**Comment by diptanshumahish** [comment]
> can u assign  me this issue? 

Hello do you want to do this page?

**Comment by RunTerror** [comment]
please assign me this issue

**Comment by RunTerror** [comment]
https://www.canva.com/design/DAFcUQaJXVI/P6HoIS1zQvEkhtKkbod6Kw/edit?utm_content=DAFcUQaJXVI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
hey @diptanshumahish  please review the cateogry page

**Comment by diptanshumahish** [comment]
> https://www.canva.com/design/DAFcUQaJXVI/P6HoIS1zQvEkhtKkbod6Kw/edit?utm_content=DAFcUQaJXVI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton hey @diptanshumahish please review the cateogry page

unable to see this, make sure its public

**Comment by RunTerror** [comment]
https://www.canva.com/design/DAFcUQaJXVI/P6HoIS1zQvEkhtKkbod6Kw/edit?utm_content=DAFcUQaJXVI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
public now

**Comment by diptanshumahish** [comment]
> https://www.canva.com/design/DAFcUQaJXVI/P6HoIS1zQvEkhtKkbod6Kw/edit?utm_content=DAFcUQaJXVI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton public now

Umm, I guess you didn't understand the content required, 😅 You see the sections like "Horror" or "picked for you" and such sections, they have an option of "show more", on clicking them the user will move to a full screen page of that category , you need to design that page.

**Comment by RunTerror** [comment]
🥲 ok will design it again

**Comment by RunTerror** [comment]
https://www.canva.com/design/DAFcoFNsHIc/IPppXPVr6Q3yiaj6wtRhEw/edit?utm_content=DAFcoFNsHIc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
hey check it 🙂

**Comment by sagnik-sanyal** [comment]
Hi @diptanshumahish i can take up this issue under JWOC

**Comment by diptanshumahish** [comment]
> https://www.canva.com/design/DAFcoFNsHIc/IPppXPVr6Q3yiaj6wtRhEw/edit?utm_content=DAFcoFNsHIc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
> 
> hey check it 🙂

Brother this one is not okay, you just copied kinda the design :( Ig for the time being i'll pass on the issue, you can work on further issues again :)
