### ISSUE TITLE
Design a settings(Profile) page for this app using dart 

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#2]
A slightly moderate difficulty task, for the Flutter developers

You have to design the settings(profile tab as per this app) page for this app, and do it by following the design  of the other pages  already existing(Don't worry about the functionalities yet , the API itself hasn't been implemented properly yet.) 

Try to design following the ios style if possible.

**Comment by LemonDrop847** [comment]
I would like to work on this.

**Comment by LemonDrop847** [comment]
Would like to work on this. @diptanshumahish

**Comment by ashishmohapatra240** [comment]
Hey, I would like to work on this issue!

Can you share the design or the Figma file, for the settings page?

**Comment by diptanshumahish** [comment]
> Hey, I would like to work on this issue!
> 
> Can you share the design or the Figma file, for the settings page?

Well I'm looking fresh ideas(ios based), in this case you might want to know what tabs(options) you need in this page , then I can say you :
1. Account option
2. Themes themes(an ios styled switch)
3. App language
4. Adult content(on and off)
5. Suggest changes option

You are free to design them as you like , but make sure it follows the IOS styles (although it will be an android app still the design principles I'm talking about),

Inside the screens folder, main screens sub-folder there is a dart file called profile.dart ,in which there is a simple button , make sure to just copy paste that functionality in the onTp for the themes option

**Comment by ashishmohapatra240** [comment]
Okay,
Working on it!

**Comment by ashishmohapatra240** [comment]
Hey, tried making the screen in iOS style,
Suggest changes or I can start coding this
![image](https://user-images.githubusercontent.com/78657461/193568470-6667f366-81dd-406a-97eb-3ca63a437b2e.png)

**Comment by diptanshumahish** [comment]
Perfect!, Just don't need the app bar or call and video call options on the top(neither the back button , because if you open the app you would find out that , this is basically a `Listview` widget you would be working on , in the profiles.dart file. There will be a bottom navigation bar below already existing , so no need for the back button) 

Make sure to either comment out the already existing code for the theme changing(onTap),or if you want you can copy paste them inside this code either , Otherwise the UI is good and clean!, you can go for it!
