### ISSUE TITLE
Add firebase login to the project

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#23]
# Add Firebase login to the project

## Keypoints
1. For now you can you firebase with your own keys, make sure to declare them as a global variables, later on we can change the keys
2. Make sure the fields are properly taken care of.
3.  For any further questions let me know.

**Comment by sagnik-sanyal** [comment]
I can start on this but the thing is that i would need firebase collaborator access , and will this issue deal with mainly login functionality only right ?

**Comment by diptanshumahish** [comment]
> I can start on this but the thing is that i would need firebase collaborator access , and will this issue deal with mainly login functionality only right ? As my PR is merged you can assign me a new issue under JWOC to work with 

Are you currently working on less than 4 other issues? If not then I can assign

**Comment by sagnik-sanyal** [comment]
Yeah i have two issues currently, if you close the favourites issue then i will have only 1 issue left

**Comment by diptanshumahish** [comment]
Okay for now you can login using your keys by registering the app on Firebase, later on I'll be sharing other kets, we can replace with them afterwards. 

btw don't include the analytics for the app from firebase

**Comment by sagnik-sanyal** [comment]
Just a suggestion it would be great if you add me as a collaborator to the firebase project , it will be very quick as i will do the setup using flutterfire cli. I wont expose the keys into github as i will add them to gitignore

**Comment by diptanshumahish** [comment]
> Just a suggestion it would be great if you add me as a collaborator to the firebase project , it will be very quick as i will do the setup using flutterfire cli. I wont expose the keys into github as i will add them to gitignore. I had already contributed to various such projects where firebase login was required they just added the collaborator permission and when it was over you can remove thereafter.

I wanted to do that as well but unfortunately I'm out of station till tomorrow, I don't have my laptop with me, so for now use your keys, ill update the keys later on, wont be an issue ig?

**Comment by sagnik-sanyal** [comment]
Then lets do one thing i am writing the basic code for the auth repository and providers , when you will be bakc just share it it wouldnt take much time using flutterfire to configure the firebase

**Comment by diptanshumahish** [comment]
> Then lets do one thing i am writing the basic code for the auth repository and providers , when you will be back you can share it wouldnt take much time using flutterfire to configure the firebase

Yup no issues with that the implementation would be pretty simple for now, later on we will add the option to update the profile pic as well, but for now just the fields on the home page and yeah the primary key would the email address. 


And the signup with google, apple and facebook, you can do that as well.( as those buttons were already made)

**Comment by sagnik-sanyal** [comment]
> > Then lets do one thing i am writing the basic code for the auth repository and providers , when you will be back you can share it wouldnt take much time using flutterfire to configure the firebase
> 
> Yup no issues with that the implementation would be pretty simple for now, later on we will add the option to update the profile pic as well, but for now just the fields on the home page and yeah the primary key would the email address.
> 
> And the signup with google, apple and facebook, you can do that as well.( as those buttons were already made)

Lets keep social login in a seperate issue as it requires some other functionality implementations as well and setup.

**Comment by sagnik-sanyal** [comment]
Hey @diptanshumahish  are you back ?

**Comment by diptanshumahish** [comment]
> Hey @diptanshumahish  are you back ?

So sorry I didn't have the network availability for last days, Yeah I'm back, please provide me your email to add as an editor on the firebase project

**Comment by sagnik-sanyal** [comment]
Yeah my email id sagniksanyal1502@gmail.com

**Comment by diptanshumahish** [comment]
> Yeah my email id [sagniksanyal1502@gmail.com](mailto:sagniksanyal1502@gmail.com)

Added you as a editor, and added the basic firebase configs, you can work on this issue now I guess

**Comment by sagnik-sanyal** [comment]
Just a question is the login ui already done ?

**Comment by diptanshumahish** [comment]
> Just a question is the login ui already done ?

yes it is, just explore the pages in the lib, you will find both the login and signup UI.(The routing earlier was directly set to home page thats why you may have missed the pages)

**Comment by sagnik-sanyal** [comment]
Hey there , i have created an auth service and wrote all the required functions to signup,login.google,apple,facebook login etc. Also there is a  stream provider to check the current auth status of the user. Also there is a global provider to set the the user properties. Is there anything that i need to address in this issue , or else i can create the PR

**Comment by diptanshumahish** [comment]
> Hey there , i have created an auth service and wrote all the required functions to signup,login.google,apple,facebook login etc. The auth service class is flexible and also there is a stream provider to check the current auth status of the user. Also there is a global provider to set the the user properties. Is there anything that i need to address in this issue , or else i can create the PR

Yes go ahead!

**Comment by diptanshumahish** [comment]
> @diptanshumahish also it would be great if can tell me my score, because we dont have any leaderboards as of now

Yes, I'll let you know ASAP.

**Comment by sagnik-sanyal** [comment]
> > @diptanshumahish also it would be great if can tell me my score, because we dont have any leaderboards as of now
> 
> Yes, I'll let you know ASAP.

Yes please waiting for your reply
