### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by utkarsh006** [diptanshumahish/watch#25]
- Update README.md by adding images of the project.
- Adding sufficient information about the repo.
- Making Readme short and concise to look.
- Assign this issue to me under JWOC.

**Comment by diptanshumahish** [comment]
> * Update README.md by adding images of the project.
> * Adding sufficient information about the repo.
> * Making Readme short and concise to look.
> * Assign this issue to me under JWOC.

So sorry for the late reply I was out of station, Yes you can write some documentation for this app, let me know if you are still up for this, I'll tell you more

**Comment by utkarsh006** [comment]
@diptanshumahish I am up for this, kindly open the issue and tell me the details to add in the readme.
