### ISSUE TITLE
Design the full screen page for the movie details 

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#28]
# Redesign the full screen page for movies/ web series details

## Keypoints
1. You can use anything, Adobe XD, FIgma etc for designing.
2. Make sure you follow the design principles of the other pages.
3. Use clean design principles.
4. For any further queries let me know.

**Comment by sagnik-sanyal** [comment]
i am ready to start designing the ui in figma under JWOC

**Comment by diptanshumahish** [comment]
> i am ready to start designing the ui in figma under JWOC

A basic page has already been built try to update on that, or if you want you can make your own designs

**Comment by sagnik-sanyal** [comment]
Where i can find that page @diptanshumahish ?

**Comment by diptanshumahish** [comment]
> Where i can find that page @diptanshumahish ?

Inside screens>mainscreenpages>fulldetails.dart

**Comment by sagnik-sanyal** [comment]
Please have a look at this https://www.figma.com/file/ulewPN9RHcvtlXFViwk4uB/Watch-Flutter?node-id=0%3A1&t=VN5sFU7wUplA7pSA-1 @diptanshumahish

**Comment by sagnik-sanyal** [comment]
@diptanshumahish can i post a PR with respect to this ui design ?
