### ISSUE TITLE
Update the Readme, and documentation for the app

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#29]
# Update the Readme and Documentation for the app

## keypoints
1. Easy opportunity for the no code people.
2. You can ask me for the exact details of the app, then you can design the Readme and Documentation
3. Avoid using AI tools for generating the text.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @diptanshumahish

**Comment by diptanshumahish** [comment]
> I want to work on this issue under JWOC @diptanshumahish 

Okay I'll assign you

**Comment by diptanshumahish** [comment]
> > I want to work on this issue under JWOC @diptanshumahish 
> 
> Okay I'll assign you

This app is basically a movie recommendation app which uses the Tmdb api to get movies or webseries data, users can search for any particular movies or get recommendations be default as well, then can login and add movies to watch list


You will have to update the readme and design it in a better way, let me know if you need more details

**Comment by Code1705** [comment]
i want to contribute to this issue by making a proper readme, already I have made readme for  deployed flutter project , please could you assign me under JWOC?

**Comment by hound77** [comment]
@diptanshumahish I want to contribute

**Comment by diptanshumahish** [comment]
> @diptanshumahish I want to contribute

Assigining tasks is on first come first serve basis, if the other person is unable or doesnt work , you will be assigned the task

**Comment by diptanshumahish** [comment]
> > @diptanshumahish I want to contribute
> 
> Assigining tasks is on first come first serve basis, if the other person is unable or doesnt work , you will be assigned the task

Read the earlier comments, and let me know if there is anything you need to know

**Comment by diptanshumahish** [comment]
> i want to contribute to this issue by making a proper readme, already I have made readme for deployed flutter project , please could you assign me under JWOC?

Read the previous comments and let me know what information you need

**Comment by Code1705** [comment]
give me the details about your app, elaborate a bit .

**Comment by Code1705** [comment]
I have created a pr , please merge it.

**Comment by diptanshumahish** [comment]
> I have created a pr , please merge it.

Merged it
