### ISSUE TITLE
Full screen page to be coded

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#35]
# code the Full screen page as follows

## keypoints
1. Code the page as [this design](https://github.com/diptanshumahish/watch/blob/master/screen_ui_designs/sagnik-sanyal-movie_page1.png) .
2. Use clean code principles.

**Comment by sagnik-sanyal** [comment]
Hello there @diptanshumahish i can work on this issue after my PR #36 is merged.

**Comment by radar101** [comment]
I want to work on this issue under the JWOC.
