### ISSUE TITLE
Text in the TextFormField is not clear

### ISSUE THREAD

**Issue by ShashankDeepak** [diptanshumahish/watch#4]
The text inside the TextFormField is not visible as shown in the image.

![Screenshot_2022-10-03-11-38-14-134_com example watch](https://user-images.githubusercontent.com/92669664/193511675-41cb6214-253a-4c26-aa12-d7bcaaadf45f.jpg)

**Comment by ShashankDeepak** [comment]
I would like to work on this issue.

**Comment by diptanshumahish** [comment]
okay that's a small fix I forgot to work hehe :),

 But you can change it , I'll tell you what to do , just go to the login-page dart file , there's a function `getTheme`() ,just copy that function here , and you can add that to the colour section for the field , BTW it's a cupertinoTextField
