### ISSUE TITLE
TmDb API integration

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#44]
# TmDB API integration (i)

## Keypoints
1. I'll be providing the API keys to be used.
2. In this first issue you need to implement the API for usage in the first page(home page).
3. Here firstly we need to check from firebase(or later maybe through local device, whether the person has added some user preferences or it is the first time logging in)
4. In case of first time the following things need to noticed that `isAdult` has to be kept `false` , we won't be having any of the userprefences, or genres chosen by the user, so we will use the following basic keywords as default genres `[horror, comedy, sci-fi, rom-com, drama]` (or any other you would like to add).
5. Make sure to call the API when the homepage opens.
6. As per as the already made page design keep those sections in mind and make the seperate api calls.
7. When the user has logged in previously and set some user preferences, then in that case instead of choosing random genres, we will be calling the API using the given keywords, and set the sections as the user choices.

**Comment by sagnik-sanyal** [comment]
I'm ready to work on this api issue under JWOC

**Comment by sagnik-sanyal** [comment]
Are we going to use v4 or v3 ?
