### ISSUE TITLE
set and get user choices from Firestore

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#45]
# set and get user choices from Firestore

## keypoints

1. You need to implement a basic functionality, that updates the firebase firestore using the user auth uid as docName, and it must have the following fields, `isAdult` (boolean), `selectedGenres` (Array of strings), `likedItems` (Array of strings).
2. Also you need to implement a way of fetching the data from firestore and storing them locally, only update it when the user updates something.

**Comment by sagnik-sanyal** [comment]
Hello i am ready to work on this issue
