### ISSUE TITLE
TmDB API Integration (ii)

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#46]
# TmDB API Integration (ii)

## keypoints
1. On clicking an movie/webseries from the homepage, the user will go to a full screen page, using the available designs and data from TmDb API you need to get the data displayed on the page.
2. Make sure to add the "like" feature on the page, when the user clicks the like button , the movie id, the liked array. 
3. On further clicking the like button, the movie/ web series must be removed from the array.
4. Many of the movies and web series do not offer a backdrop image, so so try avoiding that.

**Comment by sagnik-sanyal** [comment]
I'm ready to work on this issue under JWOC

**Comment by sagnik-sanyal** [comment]
I can work on this functionality
