### ISSUE TITLE
Movies/ web series search

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#50]
# Movies/ web series search

## keypoints
1. implement the search logic.
2. Simply take input from the `TextEditingController.text` of the text field, rather `CupertinoTextField` and make calls with the search query every time the user changes something.
3. Make sure to display some generic search results from the beginning itself when user input is empty.

**Comment by sagnik-sanyal** [comment]
I am ready to take up this issue under JWOC

**Comment by sagnik-sanyal** [comment]
Issue solved under #51

**Comment by sagnik-sanyal** [comment]
Please close this issue so as this is merged already
