### ISSUE TITLE
Issue with Hero transition in homepage under JWOC

### ISSUE THREAD

**Issue by sagnik-sanyal** [diptanshumahish/watch#52]
Yellow lines underneath the text if someone comes back from thriller section from homescreen. Need to tweak some easy stuffs there

**Comment by sagnik-sanyal** [comment]
i can work on this issue , would be a quick fix

**Comment by diptanshumahish** [comment]
yesss you can work on this, sorry got the issue closed by mistake

**Comment by sagnik-sanyal** [comment]
Ok no problem, it will be a quick fix

**Comment by sagnik-sanyal** [comment]
You can now close this issue
