### ISSUE TITLE
Firebase auth , with email password 

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#53]
# Firebase auth , with email password 

Signup page

**Comment by sagnik-sanyal** [comment]
Is this signup or login ? . I am ready to work on this issue under JWOC after my PR #54 is merged with the base branch

**Comment by diptanshumahish** [comment]
> Is this signup or login ? . I am ready to work on this issue under JWOC after my PR #54 is merged with the base branch

signup

**Comment by sagnik-sanyal** [comment]
Done please merge PR #56
