### ISSUE TITLE
Firebase login with email password

### ISSUE THREAD

**Issue by diptanshumahish** [diptanshumahish/watch#55]
# Firebase login with email password

**Comment by Prateek556** [comment]
I want to work on this issue under JWOC

**Comment by diptanshumahish** [comment]
> I want to work on this issue under JWOC

Yes go ahead and work on this, but please make sure you do it a bit fast, as we are near to the end.

**Comment by sagnik-sanyal** [comment]
I am ready to work under JWOC

**Comment by diptanshumahish** [comment]
@Prateek556 Brother, please work on this issue latest by midnight, we are already at the ending phase, we need to hurry now. Please start on this issue, if not done by midnight, I'll have to assign it to someone else.

**Comment by Prateek556** [comment]
> @Prateek556 Brother, please work on this issue latest by midnight, we are already at the ending phase, we need to hurry now. Please start on this issue, if not done by midnight, I'll have to assign it to someone else.

ok

**Comment by sagnik-sanyal** [comment]
Hi, can i start working on this implementation ?

**Comment by diptanshumahish** [comment]
> Hi, can i start working on this implementation ?

yup

**Comment by sagnik-sanyal** [comment]
Please check this PR #63
