### ISSUE TITLE
Add a SnackBar in Auth pages to display any error

### ISSUE THREAD

**Issue by ShashankDeepak** [diptanshumahish/watch#6]
I have a new suggestion - 

When you try to sign in or log in with some errors in like invalid mail or fields are left blank , there is no pop up or anything, I suggest to add a small snackbar to tell the user that what is wrong. 

It will be a lot user-friendly this way.

**Comment by ShashankDeepak** [comment]
I would like to work on this feature if accepted.

**Comment by diptanshumahish** [comment]
You can add that feature , Infact I was planning to implement that later, But anyway for the sake of hactoberfest you can add that feature now

**Comment by ShashankDeepak** [comment]
@diptanshumahish I have added the snackbar in the app, have a look at it and please tell if something more is required.

**Comment by diptanshumahish** [comment]
> @diptanshumahish I have added the snackbar in the app, have a look at it and please tell if something more is required.

Pretty good work, merged it :)
